# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/digital logic/lifegame/lifegame.cache/wt} [current_project]
set_property parent.project_path {D:/digital logic/lifegame/lifegame.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/color_generator.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/color_circlizer.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/anti_jitter.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/clock_divider.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/vga_controller.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/button_pointer.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/clock_divider_to_125ms.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/multiplexer_4_1.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/life_game.v}
  {D:/digital logic/lifegame/lifegame.srcs/sources_1/new/top.v}
}
read_xdc {{D:/digital logic/lifegame/lifegame.srcs/constrs_1/new/xdc.xdc}}
set_property used_in_implementation false [get_files {{D:/digital logic/lifegame/lifegame.srcs/constrs_1/new/xdc.xdc}}]

synth_design -top top -part xc7a35tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
