# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/number logic/lab3_2/lab3_2.cache/wt} [current_project]
set_property parent.project_path {D:/number logic/lab3_2/lab3_2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {D:/number logic/lab3_2/lab3_2.srcs/sources_1/new/clkDiv.v}
  {D:/number logic/lab3_2/lab3_2.srcs/sources_1/new/GPU.v}
  {D:/number logic/lab3_2/lab3_2.srcs/sources_1/new/shake_elimination.v}
  {D:/number logic/lab3_2/lab3_2.srcs/sources_1/new/segMsg.v}
  {D:/number logic/lab3_2/lab3_2.srcs/sources_1/new/top.v}
}
read_xdc {{D:/number logic/lab3_2/lab3_2.srcs/constrs_1/new/lab3_2.xdc}}
set_property used_in_implementation false [get_files {{D:/number logic/lab3_2/lab3_2.srcs/constrs_1/new/lab3_2.xdc}}]

synth_design -top top -part xc7a35tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
