# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/4.4_2/4.4_2.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/4.4_2/4.4_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/4.4_2/4.4_2.srcs/sources_1/new/SEG.v
  C:/Users/Administrator/Desktop/4.4_2/4.4_2.srcs/sources_1/new/GPU.v
  C:/Users/Administrator/Desktop/4.4_2/4.4_2.srcs/sources_1/new/CLKDIV.v
  C:/Users/Administrator/Desktop/4.4_2/4.4_2.srcs/sources_1/new/BUTTON.v
  C:/Users/Administrator/Desktop/4.4_2/4.4_2.srcs/sources_1/new/TOP.v
}
read_xdc C:/Users/Administrator/Desktop/4.4_2/4.4_2.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/4.4_2/4.4_2.srcs/constrs_1/new/xdc.xdc]

synth_design -top top -part xc7a35tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
