# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/ALUControl.v
  C:/Users/Administrator/Desktop/JR_Control.v
  C:/Users/Administrator/Desktop/data_memory.v
  C:/Users/Administrator/Desktop/control.v
  C:/Users/Administrator/Desktop/instr_mem.v
  C:/Users/Administrator/Desktop/alu.v
  C:/Users/Administrator/Desktop/register_file.v
  C:/Users/Administrator/Desktop/mips_16.v
}
synth_design -top mips_16 -part xc7a35tcsg324-1
write_checkpoint -noxdef mips_16.dcp
catch { report_utilization -file mips_16_utilization_synth.rpt -pb mips_16_utilization_synth.pb }
